[config]

[templates.starship-colors]
input_path = '/var/home/drew/.config/matugen/templates/starship-colors.toml'
output_path = '/var/home/drew/.config/starship.toml'

[templates.fish]
input_path = '/var/home/drew/.config/matugen/templates/fish.toml'
output_path = '/var/home/drew/.config/fish/conf.d/dankcolors.fish'

[templates.yazi]
input_path = '/var/home/drew/.config/matugen/templates/yazi.toml'
output_path = '/var/home/drew/.config/yazi/flavors/dankcolors.yazi'
