# Basic Bash configuration
# Generated by dotfiles repo

# Editor
export EDITOR="vim"
export VISUAL="vim"

# Path enhancements
export PATH="$PATH:/usr/local/bin:/home/drew/.local/bin"

# History
export HISTSIZE=1000
export HISTFILESIZE=2000
hist -a
hist -w

# Colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Terminal
export TERM="xterm-256color"

# Alias generation
alias ll="ls -la"
alias la="ls -la"
alias l="ls -l"

# Functions
pushd_home() {
    if [[ "$PWD" == "$HOME" ]]; then
        return
    fi
    cd "$HOME"
}

# PS1 with username and hostname
export PS1="\u@\h: \w $ "