# Profile configuration
# Generated by dotfiles repo

# Set default user environment
export USER_CONFIG_DIR="$HOME/.config"
export USER_DATA_DIR="$HOME/Documents"

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Language configuration
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Time zone
export TZ="America/Denver"
