# Zsh configuration
# Generated by dotfiles repo

# Editor
export EDITOR="vim"
export VISUAL="vim"

# Path
export PATH="$PATH:/usr/local/bin:/home/drew/.local/bin"

# History
export HISTSIZE=1000
export HISTFILE=~/.zhistory
hist -a
hist -w

# Colors
export CLICOLOR=1
if [[ -x /usr/bin/dircolors ]]; then
    eval "$(dircolors -b)"
fi

# Terminal
export TERM="xterm-256color"

# Completion
autoload -U compinit
compinit -C

# Zsh functions
chpwd() {
    if [[ "$PWD" == "$HOME" ]]; then
        return
    fi
}

# PS1
export PROMPT='%F{green}%n%f@%F{blue}%m%f: %F{cyan}%c%f $(git_prompt_info)$ '