context.properties = {
    # highest supported rate
    default.clock.rate = 48000
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
    default.clock.quantum = 128
    default.clock.min-quantum = 64
    default.clock.max-quantum = 8192

    # Reduce context switching overhead
    link.max-buffers = 2
}

context.modules = [
    {
        name = libpipewire-module-rtkit
        args = {
            nice.level = -11
            rt.prio = 95
            rt.time.soft = 200000
            rt.time.hard = 200000
        }
        flags = [ ifexists nofail ]
    }
]
