context.modules = [
    {   name = libpipewire-module-vban-recv
        args = {
            local.ifname = "enp7s0"
            sess.latency.msec = 12
            node.always-process = true
            node.driver = false
            audio.position = [ FL FR ]
            resample.quality = 0
            resample.disable = false
            stream.props = {
            media.class = "Audio/Source"
            node.name = "vban-receiver"
            priority.session = 100
            audio.format = "S24_3LE"
            }
            stream.rules = [
                {   matches = [ { sess.name = "~.*" } ]
                    actions = {
                        create-stream = {
                            stream.props = {
                                audio.position = [ FL FR ]
                                media.class = "Audio/Source"
                                node.name = "vban-receiver"
                                priority.session = 100
                                audio.format = "S24_3LE"
                            }
                        }
                    }
                }
            ]
        }
    }
]
