context.modules = [
  # Virtual 8-channel sink (Studio One's "outputs")
  {
    name = libpipewire-module-loopback
    args = {
      node.name = "virtual_sink"
      node.description = "Virtual 8ch Output"
      capture.props = {
        media.class = "Audio/Sink"
        audio.position = [ AUX0 AUX1 AUX2 AUX3 AUX4 AUX5 AUX6 AUX7 ]
        node.nick = "Virtual Output"
      }
      playback.props = {
        node.passive = true
        audio.position = [ AUX0 AUX1 AUX2 AUX3 AUX4 AUX5 AUX6 AUX7 ]
      }
    }
  }

  # Virtual 8-channel source (Studio One's "inputs")
  {
    name = libpipewire-module-loopback
    args = {
      node.name = "virtual_source"
      node.description = "Virtual 8ch Input"
      capture.props = {
        node.passive = true
        audio.position = [ AUX0 AUX1 AUX2 AUX3 AUX4 AUX5 AUX6 AUX7 ]
      }
      playback.props = {
        media.class = "Audio/Source/Virtual"
        audio.position = [ AUX0 AUX1 AUX2 AUX3 AUX4 AUX5 AUX6 AUX7 ]
        node.nick = "Virtual Input"
      }
    }
  }
]