PATH=/var/home/drew/.cargo/bin:/var/home/drew/.local/bin:/var/home/drew/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin
GDK_BACKEND=wayland
SSH_AUTH_SOCK=/var/home/drew/.ssh/proton-pass-agent.sock
OPENCODE_SERVER_PASSWORD="Wizards2-Only3-Fools4"
